// AUTO-GENERATED by Projects/WikiExport — do not edit by hand.
// This placeholder defines the contract until the exporter emits the real file.

export interface ItemDto {
  id: string;
  name: string;
  itemId: number;
  hue: number;
  slot: string | null;
  material: string | null;
  rarityTier: string | null;
  weight: number;
  props: Record<string, string>;
  sprite: string;
}

export interface MonsterDto {
  id: string;
  name: string;
  body: number;
  hue: number;
  hits: number;
  str: number;
  dex: number;
  int: number;
  skills: Record<string, number>;
  observedLoot: string[];
  sprite: string;
}
