import { Service } from '@angular/core';
import { httpResource } from '@angular/common/http';

import { ItemDto, MonsterDto } from '../models/generated';

// Single access point for exporter output. Every dataset is a static JSON file under
// public/data/, regenerated by Projects/WikiExport — no live API.
@Service()
export class WikiData {
  readonly items = httpResource<ItemDto[]>(() => 'data/items.json', { defaultValue: [] });
  readonly monsters = httpResource<MonsterDto[]>(() => 'data/monsters.json', { defaultValue: [] });
}
